version: '3.7'

services:

  mock:
    image: chrispsheehan/example-mock:6d94d1
    container_name: mock
    volumes:
      - ./state/state.json:/state.json
    ports: 
      - "8080:8080"
    environment:
      MOCK_REFERENCE: USER_API
    healthcheck:
      test: "curl --fail http://localhost:8080/health || exit 1"
      retries: 5
      timeout: 2s
    networks: 
      - mockservice       

  builder:
    image: node:16.5-alpine
    container_name: builder
    volumes:
      - ./:/app
    command: npm run build --prefix /app

  k6-runner:
    depends_on:
      builder:
        condition: service_completed_successfully
      mock:
        condition: service_healthy      
    image: loadimpact/k6
    container_name: k6-runner
    volumes:
      - ./dist:/dist
    command: run /dist/tests.js --config /dist/options/smoke.json --http-debug
    environment:
      - APP_DOMAIN=http://mock:8080      
    networks: 
      - mockservice        

networks:
    mockservice:
        name: mockservice    