on:
  push:
    branches:    
      - main
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: yarn build

      - uses: actions/upload-artifact@master
        with:
          name: dist-build
          path: dist

  test:
    env:
      MOCK_REFERENCE: 'CI'
      
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: dist-build
          path: dist

      - name: check-dist
        run: ls dist

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Run the build process with Docker
        run: /usr/bin/docker run --detach -p 8080:8080 -e MOCK_REFERENCE=CI chrispsheehan/example-mock:e0d243

      - name: Ping
        run: sleep 10 && curl localhost:8080/health

      - name: Run k6 local test
        run: /usr/bin/docker run -i -v dist:dist -e APP_DOMAIN=http://localhost:8080 loadimpact/k6 run /dist/tests.js --config /dist/options/smoke.json